export const AUTH_FORM_TYPE_LOGIN = "AUTH_FORM_TYPE_LOGIN";
export const AUTH_FORM_TYPE_REGISTRATION = "AUTH_FORM_TYPE_REGISTRATION";
export const AUTH_FORM_TYPE_FORGOT_PASSWORD = "AUTH_FORM_TYPE_FORGOT_PASSWORD";
